backend:
  name: git-gateway
  branch: master

media_folder: "assets/img/uploads"

publish_mode: editorial_workflow

collections:
  # POSTS
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
          - { label: "John Doe", value: "john_doe" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
  # Services
  - name: "service"
    label: "Service"
    folder: "_services"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
